; ===================================================================================
; PlatformIO Project Configuration for ESP32 Pomodoro Timer
; ===================================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    Wire
    SPI
